package com.example.spacetrader.entity;

public enum PoliticalSystem {
    ANARCHY, CAPITALISTSTATE, COMMUNISTSTATE, CONFEDERACY,
    CORPORATESTATE, CYBERNETICSTATE, DEMOCRACY, DICTATORSHIP,
    FASCISTSTATE, FEUDALSTATE, MILITARYSTATE, MONARCHY,
    PACIFISTSTATE, SOCIALISTSTATE, STATEOFSATORI, TECHNOCRACY,
    THEOCRACY
}
