package com.example.spacetrader.entity;

import java.io.Serializable;

public enum PoliticalSystem implements Serializable {
    ANARCHY, CAPITALISTSTATE, COMMUNISTSTATE, CONFEDERACY,
    CORPORATESTATE, CYBERNETICSTATE, DEMOCRACY, DICTATORSHIP,
    FASCISTSTATE, FEUDALSTATE, MILITARYSTATE, MONARCHY,
    PACIFISTSTATE, SOCIALISTSTATE, STATEOFSATORI, TECHNOCRACY,
    THEOCRACY
}
