package com.example.spacetrader.entity;

public enum Resource {
    NOSPECIALRESOURCES, MINERALRICH, MINERALPOOR, DESERT, LOTSOFWATER,
    RICHSOIL, POORSOIL, RICHFAUNA, LIFELESS, WEIRDMUSHROOMS,
    LOTSOFHERBS, ARTISTIC, WARLIKE
}
